# Generated by Django 3.2.7 on 2021-10-08 02:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Usuario entre 5 y 20 caracteres', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Username')),
                ('nombres', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_llegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado'), ('F', 'Finalizado'), ('R', 'Retrasado')], help_text="\n                                     Seleccione una de los 4 estados posibles del vuelo. 'A' para Activo, \n                                     'C' Cancelado, 'F' Finalizado y 'R' Retrasado ", max_length=1, verbose_name='Estado_Vuelo')),
                ('cupos', models.PositiveIntegerField()),
                ('company', models.CharField(db_column='Compañía', max_length=30)),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='vuelosApp.ciudades')),
                ('id_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='vuelosApp.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_tarjetas', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_propietario', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha_Vencimiento')),
                ('codigo', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('A', 'American Express'), ('B', 'Bank of America'), ('D', 'Diners Club'), ('M', 'MasterCard'), ('V', 'Visa')], help_text="\n                                     Seleccione una de las 5 posibles tarjetas. 'A' American Express, \n                                     'B' Bank of America, 'D' Diners Club, 'M' MasterCard y 'V' Visa ", max_length=1, verbose_name='Tipo')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reservas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelosApp.vuelos')),
            ],
        ),
    ]
