# Generated by Django 3.2.7 on 2022-03-13 00:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vuelosApp.models.tarjeta
import vuelosApp.models.vuelo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username must contain between 5 and 20 characters', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Username')),
                ('first_name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last_Name')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('1', 'Amazonía'), ('2', 'Barranquilla'), ('3', 'Bogotá'), ('4', 'Bucaramanga'), ('5', 'Cali'), ('6', 'Cartagena'), ('7', 'Cúcuta'), ('8', 'Ibagué'), ('9', 'Medellín'), ('10', 'Neiva'), ('11', 'Pamplona'), ('12', 'Quibdó'), ('13', 'Risaralda'), ('14', 'San Andrés'), ('15', 'Villavicencio')], max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('fecha_llegada', models.DateTimeField(blank=True, default=vuelosApp.models.vuelo.two_hours_hence)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=500000, max_digits=10)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado'), ('F', 'Finalizado'), ('R', 'Retrasado')], help_text="\n                              Seleccione una de los 4 estados posibles del vuelo. \n                              'A' para Activo, 'C' Cancelado, 'F' Finalizado y 'R' Retrasado.", max_length=1, verbose_name='Estado_Vuelo')),
                ('cupos', models.PositiveIntegerField(blank=True, default=50)),
                ('company', models.CharField(max_length=30)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='vuelosApp.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='vuelosApp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_propietario', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha_Vencimiento')),
                ('codigo', models.CharField(blank=True, default=vuelosApp.models.tarjeta.code_gen, max_length=3)),
                ('tipo', models.CharField(blank=True, choices=[('A', 'American Express'), ('B', 'Bank of America'), ('D', 'Diners Club'), ('M', 'MasterCard'), ('V', 'Visa')], default=('A', 'American Express'), help_text="\n                            Pick one out of five possible card types. 'A' American Express, \n                            'B' Bank of America, 'D' Diners Club, 'M' MasterCard and 'V' Visa.\n                            ", max_length=1, verbose_name='Tipo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_user', to=settings.AUTH_USER_MODEL)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_vuelo', to='vuelosApp.vuelo')),
            ],
        ),
    ]
