# Generated by Django 4.0.6 on 2024-02-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='puestos',
            field=models.IntegerField(default=1),
        ),
    ]
