# Generated by Django 3.2.7 on 2021-10-08 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjetas',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='vuelos',
            old_name='id_destino',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='vuelos',
            old_name='id_origen',
            new_name='origen',
        ),
        migrations.AlterField(
            model_name='reservas',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='id_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_vuelo', to='vuelosApp.vuelos'),
        ),
    ]
