# Generated by Django 3.2.7 on 2021-10-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0002_auto_20211008_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='reservas',
            old_name='id_vuelo',
            new_name='vuelo',
        ),
    ]
