# Generated by Django 3.2.7 on 2022-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0002_alter_tarjeta_nombre_propietario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='cupos',
            new_name='_cupos',
        ),
        migrations.AddField(
            model_name='reserva',
            name='puestos',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'American Express'), ('B', 'Bank of America'), ('D', 'Diners Club'), ('M', 'MasterCard'), ('V', 'Visa')], default='A', help_text="\n                            Pick one out of five possible card types. 'A' American Express, \n                            'B' Bank of America, 'D' Diners Club, 'M' MasterCard and 'V' Visa.\n                            ", max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado'), ('F', 'Finalizado'), ('R', 'Retrasado')], default='A', help_text="\n                              Seleccione una de los 4 estados posibles del vuelo. \n                              'A' para Activo, 'C' Cancelado, 'F' Finalizado y 'R' Retrasado.", max_length=1, verbose_name='Estado_Vuelo'),
        ),
    ]
