# Generated by Django 4.0.6 on 2022-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0005_alter_reserva_puestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='puestos',
            field=models.IntegerField(default=1),
        ),
    ]
