# Generated by Django 3.2.7 on 2021-10-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0005_auto_20211015_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='nombre',
            field=models.CharField(choices=[('1', 'Amazonía'), ('2', 'Barranquilla'), ('3', 'Bogotá'), ('4', 'Bucaramanga'), ('5', 'Cali'), ('6', 'Cartagena'), ('7', 'Cúcuta'), ('8', 'Ibagué'), ('9', 'Medellín'), ('10', 'Neiva'), ('11', 'Pamplona'), ('12', 'Quibdó'), ('13', 'Risaralda'), ('14', 'San Andrés'), ('15', 'Villavicencio')], max_length=30, unique=True),
        ),
    ]
