# Generated by Django 3.2.7 on 2021-10-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0006_alter_ciudades_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vuelo',
            field=models.ManyToManyField(through='vuelosApp.Reservas', to='vuelosApp.Vuelos'),
        ),
    ]
