# Generated by Django 3.2.7 on 2021-10-24 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0007_user_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='vuelo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vuelosApp.vuelos'),
        ),
    ]
