# Generated by Django 3.2.7 on 2021-10-28 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0008_auto_20211024_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vuelo',
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
