# Generated by Django 3.2.7 on 2021-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0009_auto_20211028_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='codigo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_Vencimiento'),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='id_tarjetas',
            field=models.IntegerField(blank=True, default=-9999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='nombre_propietario',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'American Express'), ('B', 'Bank of America'), ('D', 'Diners Club'), ('M', 'MasterCard'), ('V', 'Visa')], help_text="\n                                     Seleccione una de las 5 posibles tarjetas. 'A' American Express, \n                                     'B' Bank of America, 'D' Diners Club, 'M' MasterCard y 'V' Visa ", max_length=1, verbose_name='Tipo'),
        ),
    ]
