# Generated by Django 3.2.7 on 2021-10-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0010_auto_20211028_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'American Express'), ('B', 'Bank of America'), ('D', 'Diners Club'), ('M', 'MasterCard'), ('V', 'Visa')], default='A', help_text="\n                                     Seleccione una de las 5 posibles tarjetas. 'A' American Express, \n                                     'B' Bank of America, 'D' Diners Club, 'M' MasterCard y 'V' Visa ", max_length=1, verbose_name='Tipo'),
        ),
    ]
