# Generated by Django 3.2.7 on 2021-10-31 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0016_auto_20211029_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelosApp.vuelos'),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='company',
            field=models.CharField(max_length=30),
        ),
    ]
