# Generated by Django 3.2.7 on 2021-10-31 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuelosApp', '0017_auto_20211031_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_vuelo', to='vuelosApp.vuelos'),
        ),
    ]
